# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-13 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PPMS', '0003_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNo', models.CharField(max_length=10)),
                ('password', models.CharField(default=b'', max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
