# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMS', '0009_auto_20240329_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='id',
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
