# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-07 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=b'', max_length=10),
        ),
    ]
