# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMS', '0002_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('amenities', models.TextField()),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'venue_images/')),
            ],
        ),
    ]
