# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-28 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPMS', '0004_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
    ]
